version: '3'

services:
  api-heroes-postgres:
    container_name: api-heroes-postgres
    build: .
    command: npm run dev
    ports:
      - 3000:3000
    environment:
      POSTGRES_HOST: postgres:root@127.0.0.1:5432
      PORT: 3000

    depends_on:
      - postgres
    links:
      - postgres

  postgres:
    container_name: postgres
    restart: always
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: project_node
