version: '3.7'

services:
  app:
    container_name: app
    build: .
    command: sh -c "npm i && npm run dev"
    volumes:
      - .:/usr/app
    ports:
      - "3001:3001"
    depends_on:
      - database
    links:
      - database
  database:
    image: postgres
    container_name: database
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: