version: '3.7'

services:
  app:
    container_name: app
    build: .
    command: npm run dev
    volumes:
      - .:/usr/app
    ports:
      - "3001:3001"
    depends_on:
      - database
    links:
      - database
  database:
    image: postgres
    container_name: database
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=teste
      - POSTGRES_PASSWORD=teste
      - POSTGRES_DB=project_node
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: